Add ameba and rework output

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,20 +1,12 @@
 #!/bin/sh
 
 changed_cr_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.cr$')
-[ -z "$changed_cr_files" ] #&& exit 0
+[ -z "$changed_cr_files" ] && exit 0
 
-crystal tool format --check $changed_cr_files >/dev/null
-ret_code=$?
+crystal tool format $changed_cr_files
 
-if [ 0 -ne $ret_code ]; then
-  echo "Files need formatting. Use \`crystal tool format\` and recommit."
-  exit $ret_code
-fi
+shards check || exit 1
 
-crystal spec --fail-fast >/dev/null
-ret_code=$?
+bin/ameba -f flycheck $changed_cr_files || exit 1
 
-if [ 0 -ne $ret_code ]; then
-  echo "Specs failed. Ensure specs pass and recommit."
-  exit $ret_code
-fi
+crystal spec --fail-fast >/dev/null || echo "Specs failed."; exit 1
